# Generated by Django 3.2.9 on 2021-12-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_nr', models.CharField(max_length=10)),
                ('make', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=120)),
                ('co2', models.IntegerField()),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='instances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_nr', models.CharField(max_length=120)),
                ('location_id', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarList.location'))),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('no_passangers', models.IntegerField(blank=True, default='', null=True)),
                ('impath', models.CharField(max_length=255)),
                ('isvalid', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'instances',
            },
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=120)),
                ('zip', models.IntegerField()),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='samgongustofa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permno', models.CharField(blank=True, max_length=50, null=True)),
                ('regno', models.CharField(blank=True, max_length=50, null=True)),
                ('vin', models.CharField(blank=True, max_length=50, null=True)),
                ('make', models.CharField(blank=True, max_length=120, null=True)),
                ('model', models.CharField(blank=True, max_length=120, null=True)),
                ('color', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('vehicleStatus', models.CharField(blank=True, max_length=120, null=True)),
                ('nextVehicleMainInspection', models.DateField(blank=True, null=True)),
                ('co2', models.IntegerField(blank=True, null=True)),
                ('weightedCo2', models.IntegerField(blank=True, null=True)),
                ('co2WLTP', models.IntegerField(blank=True, null=True)),
                ('weightedCo2WLTP', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('massLaden', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'samgongustofa',
            },
        ),
    ]
